apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eks-demo-app-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: eks-demo-app
  namespaceSelector:
    matchNames:
      - eks-demo-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
