apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: eks-demo-app
data:
  ENVIRONMENT: "production"
  APP_VERSION: "1.0.0"
  DEPLOYMENT_TAG: "latest"  # This will be overridden dynamically by GitHub Actions
