apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo-app
  namespace: eks-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: eks-demo-app
    spec:
      containers:
        - name: eks-demo-app
          image: 556152725477.dkr.ecr.us-east-1.amazonaws.com/flaskapp-nayapay-1:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: flask-config
            - secretRef:
                name: flask-secrets
