apiVersion: v1
kind: Service
metadata:
  name: eks-demo-app
  namespace: eks-demo-app
spec:
  type: ClusterIP       # Changed from LoadBalancer
  selector:
    app: eks-demo-app
  ports:
    - port: 80          # Cluster-internal port
      targetPort: 5000  # Container port
      protocol: TCP
