apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-demo-app-ingress
  namespace: eks-demo-app
  annotations:
    kubernetes.io/ingress.class: "alb"
    # ALB-specific
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    # set health check path for ALB
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/healthcheck-port: "5000"
    # enable stickiness if you need it in future:
    # alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eks-demo-app-service
                port:
                  number: 80
